apiVersion: v1
data:
  SECRET_DATA_1: TGFraQ==
  SECRET_DATA_2: bGFraUB0aC5pYm0uY29t
kind: Secret
metadata:
  creationTimestamp: 2019-10-24T05:09:16Z
  name: secret-1
  namespace: poc
  resourceVersion: "707676"
  selfLink: /api/v1/namespaces/poc/secrets/secret-1
  uid: 6d7d5d5f-f61c-11e9-981c-42010a9400ff
type: Opaque
