version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./postgre/postgres-data:/var/lib/postgresql/data
      - ./postgre/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: P@ssw0rd
      DB_PORT: 5432
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROVIDER_LOGLEVEL: DEBUG
      KEYCLOAK_ENV: developement
    ports:
      - "8080:8080"
    depends_on:
      - db
  openldap:
    image: osixia/openldap:1.3.0
    restart: always
    volumes:
      - ./openldap/data/slapd/database:/var/lib/ldap
      - ./openldap/data/slapd/config:/etc/ldap/slapd.d
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    ports:
      - "8083:80"
      - "8483:443"
  # test:
  #   image: test:latest
  #   restart: always
  #   ports:
  #     - "80:80"
  # redis:
  #   restart: always
  #   image: redis:alpine3.10
  #   volumes:
  #     - ./redis/data:/data
  #     - ./redis/config:/usr/local/etc/redis
  # gitlab:
  #   image: 'gitlab/gitlab-ce:12.4.2-ce.0'
  #   restart: always
  #   hostname: 'gitlab.example.com'
  #   depends_on:
  #     - redis
  #     - db
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       postgresql['enable'] = false
  #       gitlab_rails['db_username'] = "gitlab"
  #       gitlab_rails['db_password'] = "P@ssw0rd"
  #       gitlab_rails['db_host'] = "db"
  #       gitlab_rails['db_port'] = "5432"
  #       gitlab_rails['db_database'] = "gitlabhq_production"
  #       gitlab_rails['db_adapter'] = 'postgresql'
  #       gitlab_rails['db_encoding'] = 'utf8'
  #       redis['enable'] = false
  #       gitlab_rails['redis_host'] = 'redis'
  #       gitlab_rails['redis_port'] = '6379'
  #       external_url 'http://gitlab.example.com:8084'
  #       gitlab_rails['gitlab_shell_ssh_port'] = 8085
  #   ports:
  #     - "8084:8084"
  #     - "8085:22"
  #   volumes:
  #     - ./gitlab/config:/etc/gitlab:rw
  #     - ./gitlab/logs:/var/log/gitlab:rw
  #     - ./gitlab/data:/var/opt/gitlab:rw
  # sonarqube:
  #   image: sonarqube:7.9.1-community
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - sonar.jdbc.username=sonarqube
  #     - sonar.jdbc.password=P@ssw0rd
  #     - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
  #   volumes:
  #     - ./sonar/config:/opt/sonarqube/conf
  #     - ./sonar/data:/opt/sonarqube/data
  #     - ./sonar/extensions:/opt/sonarqube/extensions
  # nexus:
  #   image: sonatype/nexus3:3.19.1
  #   restart: always
  #   volumes:
  #     - ./nexus/data:/nexus-data
  #     - ./nexus/home/nexus:/opt/sonatype/nexus
  #   ports:
  #     - "8085:8081"
  # landing:
  #   image: ibmlakisik/ktb:devops_landing.v1.0.0
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - "8086:9000"